### ISSUE TITLE
"clb is not a function" when using effect or watch

### ISSUE THREAD

**Issue by Darkle** [kutlugsahin/re-active#25]
Hi, I seem to be getting an error message of `clb is not a function` when I use either `effect` or `watch`.

I have created a simple test repo here: https://github.com/Darkle/re-active-test
Just run `npm install` and then `npm start` and then open the page and check the browser console.

**Comment by kutlugsahin** [comment]
Hi, it is fixed in the version 1.1.4. Thanks for giving a try :)
